AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Hummingbird Lambda functions.

Globals:
    Function:
        Timeout: 3
        MemorySize: 128

Resources:
    hbLambdaTestFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: swift.bootstrap
            Runtime: provided.al2
            Architectures:
                - arm64
            CodeUri: ../.build/plugins/AWSLambdaPackager/outputs/AWSLambdaPackager/HBLambdaTest/HBLambdaTest.zip
            Environment:
                Variables:
                    # by default, AWS Lambda runtime produces no log
                    # use `LOG_LEVEL: debug` for for lifecycle and event handling information
                    # use `LOG_LEVEL: trace` for detailed input event information
                    LOG_LEVEL: trace
            # Instructs new versions to be published to an alias named "live".
            # AutoPublishAlias: live
            Events:
                HttpApiEvent:
                    Type: HttpApi

Outputs:
    HttpApi:
        Description: "API Gateway endpoint URL for Prod stage"
        Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
