name: Deploy Example

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.9-amazonlinux2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Archive
        run: |
          swift build
          swift package archive
