name: Swift nightly build

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['nightly-5.4-amazonlinux2']
    container:
      image: swiftlang/swift:${{ matrix.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        swift build
